apiVersion: v1
kind: Secret
metadata:
  name: temptest-tls
  namespace: default
type: kubernetes.io/tls
data:
  server.crt: |
-----BEGIN CERTIFICATE-----
MIIEBzCCAu+gAwIBAgIUIIIa7KBy76LE+g1Q2gWq90oJBNMwDQYJKoZIhvcNAQEL
BQAwgZIxCzAJBgNVBAYTAlRIMRAwDgYDVQQIDAdCYW5na29rMRAwDgYDVQQHDAdC
YW5na29rMREwDwYDVQQKDAhYWVogSW5jLjESMBAGA1UECwwJVGVjaCBUZWFtMRgw
FgYDVQQDDA8qLmV4YW1wbGUubG9jYWwxHjAcBgkqhkiG9w0BCQEWD2FkbWluQGdt
YWlsLmNvbTAeFw0yNDA2MjcwODQ2NTNaFw0yNTA2MjcwODQ2NTNaMIGSMQswCQYD
VQQGEwJUSDEQMA4GA1UECAwHQmFuZ2tvazEQMA4GA1UEBwwHQmFuZ2tvazERMA8G
A1UECgwIWFlaIEluYy4xEjAQBgNVBAsMCVRlY2ggVGVhbTEYMBYGA1UEAwwPKi5l
eGFtcGxlLmxvY2FsMR4wHAYJKoZIhvcNAQkBFg9hZG1pbkBnbWFpbC5jb20wggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5qvLSiFG4svuq9eZIWlKyr0TP
0H8kDuebOkGSd7Q/4Erix3/gXY5+iLkJgZCUEo82dWg7bTkymebah5PgPqn9ARut
5meZ2u/ZLpyvPuJD7seA57WPf5xm1wZAhKSO9qYjRgbxGcwj3stSJiTzaIp1fUvR
OSDBt5LiSOWl9NTGdIAuPHBjHY19iyEOgMmUcyGtecJouHGgA7kcMDacPUOPNi4m
RUFHmxyJshbibuDn41UnfjeKQaPkqwFqh5NRQeQn2uRF24lBgJXzqxI2T2gQgqFU
zIqc1OM3OCCWDTozoT3wgiDp0g41ehUyoN1IAMlbaBfw0k0bPyL3AZFgoLNdAgMB
AAGjUzBRMB0GA1UdDgQWBBR8u7VcH3p85CovJUIvivO3/5oN5TAfBgNVHSMEGDAW
gBR8u7VcH3p85CovJUIvivO3/5oN5TAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3
DQEBCwUAA4IBAQBzHEtPNCcf1ATbrda5fw8GCcDPj5twyjY7+znHZ7XPDzLCSimr
7oTpxtFTrteR48IA6RletmpyY0UPsuEYkb0U4XDyzSwjsdSU6AqQIsc0+w7xciH+
JyLKl2nXjjTcEZ+EdMtGOtjkg7lcnJRaAf6CP5uICB53VxtTzWXq+NhbYaCO830a
SVV/zvKyykOx6MHz+76k4nWOhodjq1WONy8gKE+tand4sWrzG/1S944WZv+yytkU
6ovugTNsnq7g5wyel3O2A1q1KJym8wiiCrCw83zHC41KjfRf2BwBr2LcItkonulS
qkT/2qQmYrwg0WvM7Y5NtHGI/rxiqtUq5qb/
-----END CERTIFICATE-----
  server.key: |
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC5qvLSiFG4svuq
9eZIWlKyr0TP0H8kDuebOkGSd7Q/4Erix3/gXY5+iLkJgZCUEo82dWg7bTkymeba
h5PgPqn9ARut5meZ2u/ZLpyvPuJD7seA57WPf5xm1wZAhKSO9qYjRgbxGcwj3stS
JiTzaIp1fUvROSDBt5LiSOWl9NTGdIAuPHBjHY19iyEOgMmUcyGtecJouHGgA7kc
MDacPUOPNi4mRUFHmxyJshbibuDn41UnfjeKQaPkqwFqh5NRQeQn2uRF24lBgJXz
qxI2T2gQgqFUzIqc1OM3OCCWDTozoT3wgiDp0g41ehUyoN1IAMlbaBfw0k0bPyL3
AZFgoLNdAgMBAAECggEAE0mG4Af5NU6ihif1PB7l6Fn8s/ncu0oxFRcAKM72kowi
O1yuFAij/NEHJ82lzzv+VJHtuf6mqnMCYEElQ24/CmFLFs2QhZMQx2boL+xAZP4x
C1sGqVmATc6Yf6tHzPIiYBeuMO2VH0TNqkL8I60AdSQG9D0TAgyn3YnlEVBVqifS
qhc2nqJHSPTeBgV3hNKbPAJmPh51mmU9guUUHQ3DFk/wd4MxAv4czNKMMX2NokRh
PcMd/CGhXreWaN/P3Qv5k+q5iWwaRSam2Xrm6C0z53zfO7nAdMzRUyWrx5sSvtdR
624f9y1iA6Ca9yaZGbgQ34A5N2fhCpXUHxTgGnxroQKBgQDm6qld6Z9I08tICtb4
iiWVPT3tnJFwMastN0DK/8SZa4nAIR2XcIM/imSDSHEmWS6uPS91BhIzTWlPXYD4
BKvYSENIb7EJWKkfEK7tEmzcFmfBS1pnZ2r26A76yO+4o6ZPkb0pMZlFJkeMDNHc
L5ciFY3E5L0x4t7W/1aBHadpHwKBgQDN1gElgeHrMnewS22+mp4quR8rHTKZA3Jr
s4DBQ/WAK/uXjeRCbO+Pk1UPFndLQoWXfiYCBKao1OOlZiLbMREicG1J215nMego
9/oGVyvLRi8UDoXVpqAkQ3dm4Z1EbGfM4B8WNEKq8Go9poB66qTRZ4D0AE8l9QjO
Vv3SA+6IAwKBgBhnSErie7DooR0V+C3/+4TQGhFYcI5Y0WxP4IsTiKVmFgK1/TiZ
7WTzrTeqmjqhRiunz7IgWCAP2EdI7G5JoBeVW3b2RtFkC0t7KeFoBxUjUQe+fOlc
ppM9Zwfd4Ge088iI8GLAGSCTsQ/98tfAN8qkWH0sZ0o0XbR++5ddmOmlAoGAROLj
HVdbcWhBcCm+P7TlTC0KRlaOMXFa4LqBU6zXw550o+LjymtEvUs0g0kkgXZw2SNp
uvEtiYE98oO9FJhWQK1Zlgcpj+W+6b8b2PVhfbUuWksF9Vu/aoN9uVu2U0jocENt
g/PXf/fXxmwrwXc307ENEhvsYSqhWNT6O0f/k1sCgYA5Cv0+zXLQ6TjlDGm5yeTI
42Rpn95Uxc1Nzwx9gi2YtYAt4wbISDBOWt96TLh+rAuKwOR+5x5Mq9lvuDGgqArS
idAH57S327tCi0GJ58RlP4TqepdutYGA5Q2/xXZdyps7RTfFPxchRtJBVxv0mclH
lWLtAwwwRtF13hrftBt2fg==
-----END PRIVATE KEY-----